theory Core_Local_Charts
  imports Main
begin

locale coordinate_atlas =
  fixes E :: "'t set" and Charts :: "'i set"
    and TD :: "'i \<Rightarrow> 't set" and TT :: "'i \<Rightarrow> 'theta set"
    and ID :: "'i \<Rightarrow> 'vin set" and IT :: "'i \<Rightarrow> 'nin set"
    and OD :: "'i \<Rightarrow> 'vout set" and OT :: "'i \<Rightarrow> 'nout set"
    and tc :: "'i \<Rightarrow> 't \<Rightarrow> 'theta"
    and ic :: "'i \<Rightarrow> 'vin \<Rightarrow> 'nin"
    and oc :: "'i \<Rightarrow> 'vout \<Rightarrow> 'nout"
    and fin :: "'t \<Rightarrow> 'vin" and fout :: "'t \<Rightarrow> 'vout"
  assumes time_chart: "i \<in> Charts \<Longrightarrow> bij_betw (tc i) (TD i) (TT i)"
    and input_chart: "i \<in> Charts \<Longrightarrow> bij_betw (ic i) (ID i) (IT i)"
    and output_chart: "i \<in> Charts \<Longrightarrow> bij_betw (oc i) (OD i) (OT i)"
    and time_domain: "i \<in> Charts \<Longrightarrow> TD i \<subseteq> E"
    and coverage: "t \<in> E \<Longrightarrow> \<exists>i\<in>Charts.
      t \<in> TD i \<and> fin t \<in> ID i \<and> fout t \<in> OD i"
begin

definition joint where "joint i = {t \<in> TD i. fin t \<in> ID i \<and> fout t \<in> OD i}"
definition numeric where "numeric i = tc i ` joint i"
definition inverse where "inverse i = inv_into (joint i) (tc i)"
definition source_values where "source_values i t = (ic i (fin t), oc i (fout t))"
definition curve where "curve i theta = source_values i (inverse i theta)"

lemma time_value_injective:
  "i \<in> Charts \<Longrightarrow> inj_on (tc i) (joint i)"
  using time_chart by (auto simp: bij_betw_def joint_def intro: inj_on_subset)

lemma time_coordinate_bijective:
  "i \<in> Charts \<Longrightarrow> bij_betw (tc i) (joint i) (numeric i)"
  using time_value_injective by (simp add: bij_betw_def numeric_def)

lemma inverse_left:
  "i \<in> Charts \<Longrightarrow> t \<in> joint i \<Longrightarrow> inverse i (tc i t) = t"
  using time_value_injective by (simp add: inverse_def inv_into_f_f)

lemma inverse_right:
  "theta \<in> numeric i \<Longrightarrow> tc i (inverse i theta) = theta"
  by (simp add: inverse_def numeric_def f_inv_into_f)

lemma coordinate_curve_generated:
  "i \<in> Charts \<Longrightarrow> t \<in> joint i \<Longrightarrow>
    curve i (tc i t) = source_values i t"
  by (simp add: curve_def inverse_left)

lemma side_curve_generated:
  "i \<in> Charts \<Longrightarrow> t \<in> joint i \<Longrightarrow>
    fst (curve i (tc i t)) = ic i (fin t) \<and>
    snd (curve i (tc i t)) = oc i (fout t)"
  by (simp add: coordinate_curve_generated source_values_def)

lemma curve_unique:
  assumes "i \<in> Charts" and "\<And>t. t \<in> joint i \<Longrightarrow> g (tc i t) = source_values i t"
  shows "\<forall>theta\<in>numeric i. g theta = curve i theta"
  using assms coordinate_curve_generated by (auto simp: numeric_def)

lemma joint_domain_coverage:
  "t \<in> E \<Longrightarrow> \<exists>i\<in>Charts. t \<in> joint i"
  using coverage by (auto simp: joint_def)

lemma generation_at_every_time:
  "t \<in> E \<Longrightarrow> \<exists>i\<in>Charts. t \<in> joint i \<and>
    curve i (tc i t) = source_values i t"
  using joint_domain_coverage coordinate_curve_generated by blast

lemma inverse_agrees_with_time_chart:
  assumes hi: "i \<in> Charts" and ht: "theta \<in> numeric i"
  shows "theta \<in> TT i \<and> inv_into (TD i) (tc i) theta = inverse i theta"
proof -
  obtain t where t: "t \<in> joint i" "theta = tc i t"
    using ht by (auto simp: numeric_def)
  have td: "t \<in> TD i" using t by (simp add: joint_def)
  have inj: "inj_on (tc i) (TD i)" using time_chart[OF hi] by (simp add: bij_betw_def)
  have inv: "inv_into (TD i) (tc i) (tc i t) = t" using inj td by (rule inv_into_f_f)
  have image: "tc i t \<in> TT i" using time_chart[OF hi] td by (auto simp: bij_betw_def)
  show ?thesis using image inv inverse_left[OF hi t(1)] t(2) by simp
qed

lemma curve_values_typed:
  assumes hi: "i \<in> Charts" and ht: "theta \<in> numeric i"
  shows "curve i theta \<in> IT i \<times> OT i"
proof -
  obtain t where t: "t \<in> joint i" "theta = tc i t"
    using ht by (auto simp: numeric_def)
  have hin: "ic i (fin t) \<in> IT i"
    using input_chart[OF hi] t by (auto simp: joint_def bij_betw_def)
  have hout: "oc i (fout t) \<in> OT i"
    using output_chart[OF hi] t by (auto simp: joint_def bij_betw_def)
  show ?thesis using coordinate_curve_generated[OF hi t(1)] hin hout t(2)
    by (simp add: source_values_def)
qed
end

ML \<open>
val roots = @{thms coordinate_atlas.time_value_injective coordinate_atlas.time_coordinate_bijective coordinate_atlas.inverse_left coordinate_atlas.inverse_right coordinate_atlas.coordinate_curve_generated coordinate_atlas.side_curve_generated coordinate_atlas.curve_unique coordinate_atlas.joint_domain_coverage coordinate_atlas.generation_at_every_time coordinate_atlas.inverse_agrees_with_time_chart coordinate_atlas.curve_values_typed};
if null (Thm_Deps.all_oracles roots) then () else error "Unexpected oracle dependency";
\<close>
end
