theory Native_Law_Jet_Alignment
  imports "LCTR_Modeled_Source_Value_Change.Modeled_Source_Value_Change"
begin

lemmas realization_value_in_chart = native_real_component_chart.realization_value_in_chart
lemmas zeroth_is_generated_curve = Native_Law_Jet_Core.zeroth_is_generated_curve
lemmas zeroth_is_native_law_value = native_real_component_chart.zeroth_is_native_law_value
lemmas smooth_realizations_agree_nearby = Native_Law_Jet_Core.smooth_realizations_agree_nearby
lemmas native_jet_independent_of_extension = Native_Law_Jet_Core.native_jet_independent_of_extension
lemmas generated_jet_relation_membership = Native_Law_Jet_Core.generated_jet_relation_membership
lemmas value_change_acts_on_native_jet = native_real_component_chart.value_change_acts_on_native_jet
lemmas value_covariance_preserves_native_membership = modeled_native_membership zero_source_native_membership
lemmas time_change_preserves_native_zeroth = native_real_component_chart.time_change_preserves_native_zeroth
lemmas time_covariance_preserves_native_membership = native_real_component_chart.time_covariance_preserves_native_membership

ML \<open>
val roots = @{thms realization_value_in_chart zeroth_is_generated_curve zeroth_is_native_law_value smooth_realizations_agree_nearby native_jet_independent_of_extension generated_jet_relation_membership value_change_acts_on_native_jet value_covariance_preserves_native_membership time_change_preserves_native_zeroth time_covariance_preserves_native_membership};
val _ = if null (Thm_Deps.all_oracles roots) then () else error "Unexpected oracle dependency";
\<close>
end
